### ISSUE TITLE
Feature Request: Stretch spaces by a fixed amount.

### ISSUE THREAD

**Issue by subhav** [kylepaulsen/vscode-stretchy-spaces#8]
Could we add an option to set each space's letterSpacing to a fixed amount, rather than setting a target for each tabstop?

This would still be useful for proportional-width fonts where the space character is too narrow to be used to indent code. (Also, the target calculation is broken for proportional-width fonts, anyway.)

**Comment by kylepaulsen** [comment]
I am confused why you would want to use proportional-width fonts in a code editor, but to each their own I suppose.

We could maybe have an option like `customStretch` or something that just directly sets the letter spacing. It's important to note however that it wont be exact (for example if you set it to 0px, one space would still actually have some amount of width - maybe around 7 pixels or so). Also changing to another proportional-width font would probably require "recalibrating" the new setting to be what you want. Finally, this setting would not adjust based on the current file's indentation but maybe that's what you want anyway. So maybe we can do this if this fixes your issue.

I'm not sure how else to fix this issue otherwise, I definitely wasn't counting on people using anything but monospaced fonts when I made this.

**Comment by subhav** [comment]
Yup, that sounds good to me!

I don't normally use proportional fonts, but I'd like to. It should be comfortable with the right editor support.

I'm not really picky about having the spaces be fixed like this, but the normal behavior of this extension is broken with proportional fonts, and this would work as well for me. (`1ch` isn't the width of a space, so too much spacing is added/removed.)

**Comment by subhav** [comment]
In retrospect, this is a pretty weird FR given the scope of the extension. Probably not worth leaving this open.
